### ISSUE TITLE
Error message: Corrupted file

### ISSUE THREAD

**Issue by SimonEast** [Darmo117/TI-83_Compiler#2]
Not sure if this repo is maintained anymore, but I was just trying out your decompiler on a program I wrote using the official "TI Connect CE" app and got the message `Corrupted file`.

TEST.8XP source code:

```
Disp 1+1
```

Commands run:

```
java -jar TI-83_Compiler-1.2.jar -f test.8xp -u en
```

Output:

```
** TI-83 Compiler/Decompiler v1.2 **
Corrupted file.
```

The program runs fine on emulator and calculator, so it must be some kind of compatibility issue with TI-83_Compiler.

Here is my source file: [temp2.zip](https://github.com/Darmo117/TI-83_Compiler/files/8137737/temp2.zip)

**Comment by DamiaV** [comment]
Hi, I never thought anyone would use this tool ^^
I haven’t touched this project in years, I’ll try to investigate the issue.

**Comment by DamiaV** [comment]
I just released a new version (1.2.1) that should hopefully fix the issue. Can you test it and tell me if it works on your side so that I can close this issue? Thanks!

**Comment by SimonEast** [comment]
Haha, yes, TI-83/43 programming does seem to be declining, but I needed a physical calculator for work and it's still the best one I've come across (I don't need color and prefer the longer battery life), so have been getting back into building apps for myself. Thanks for taking the time to look into it. I will have another try over the next week or so when I get the chance.

**Comment by SimonEast** [comment]
Thanks for the fix, Damien. Decompiling works now. 😄👍 

I did find a few small quirks with the **decompiler from 8XP**:

* The version number output to the console hasn't been updated (minor)
* Strings containing an `&` or `~` characters cause decompilation to fail with `Corrupted file: Unknown token 0xbb`
* Strings with lowercase letters have many underscores inserted into each string, e.g.:

   `"Here is a text comment"` ...becomes... `"H_e_r_e i_s _a _t_ex_t _comm_e_n_t"`

There's a [full list of TI-83 tokens and hex codes here](https://gist.github.com/SimonEast/78e8ee29b2bf6c8c9bb34b0cbda00fd0) if that's a helpful reference.

When **compiling to 8XP**, I noticed that:

* Strings containing a lowercase `i` were compiled into the curly/italics `i` which is not quite correct, although I think the way you've done it seems correct for lowercase `i` _outside_ a string.
* Similar thing for lowercase `n` used inside a string

Otherwise it worked quite superbly, and I'm impressed at how it handled a large number of advanced functions and tokens. Thanks for the excellent work! 👏 

If I can get a few of these bits ironed out, I may build another library on top of yours to provide nicer syntax for things like subroutines, longer variable names, and compile-time templates.

I'd consider having a go at fixing these issues myself, but I'm a bit rusty in Java, so it might take me a while. I also understand if these bugs are not something you have the time or interest to fix, as it probably is a fading technology.

**Comment by DamiaV** [comment]
Thank you for the feedback :)

Some answers to your remarks:
* I indeed forgot to update the version number, that should be patched in the next version.
* I didn’t even know these characters could be typed in TI83+ calculators (in any case that is not possible on mine). After further reading the link you provided, tokens 0xBBCF through 0xBBF5 were added in versions 1.15 and 1.16 of the OS and it seems the version I have on may calculator is older and does not have them, same thing for the document sheet I used as a reference.
* That’s weird, I’ll have to investigate… To be honest the way I implemented the parsers back in 2017 was a bit of a hack job. I’m not really surprised that it breaks as it was one of the first text parsers I had ever coded ^^

Be assured, I’ll try to fix these issues ASAP.

**Comment by SimonEast** [comment]
Yeah I use a TI-84 Plus which is nearly identical to the TI-83+ in all features except it has a USB port. I use Texas’ free “TI Connect CE” app to write programs on my computer before transferring them. This works pretty well but it’s a pretty basic editor (pardon the pun!) and I’d like to build some additional features. Coding on the computer likely allows additional characters than the calculator allows you to input. But it seems that the calculators still support displaying the full ASCII set of chars even if you can’t type them all on the calc itself. 

I considered upgrading to a TI-92 but the interface is more messy and I’ve heard that they might be blocking assembly programs so the the TI-84+ might still be the most extensible.

**Comment by DamiaV** [comment]
So! I just released a [new version](https://github.com/Darmo117/TI-83_Compiler/releases/tag/v2.0) (2.0). I rewrote nearly everything so most problems should have been addressed. I also added tokens that were missing from previous versions.

I wasn’t able to test compiled programs on an actual calculator nor on any emulators as I’m on Linux and couldn’t get anything TI-related to work (ah… old Windows-only software…). Nevertheless, I’m pretty confident everything should compile fine thanks to some *heavy* unit tests.

Once again, thanks a lot for your patience ^^

**Comment by SimonEast** [comment]
Thanks for the great work! I didn't expect you to do a rewrite over this! But thank you. And sorry for taking a few weeks to try it out again.

It's working much better, and I believe the issues I noted above are mostly fixed, except I'm still noticing a few quirks with decompiling lowercase letters. For example, here's some TI-BASIC code created using TI-Connect CE:

```
"Store feet in F
.3048→F

"Convert mode to degrees
Degree

"Reset display (16x7)
ClrHome
```

When *decompiling* with your tool, it produces this:

```
"S𝗍o𝗋𝖾 f𝖾𝖾𝗍 i𝗇 F
.3048->F

"Co𝗇𝗏𝖾𝗋𝗍 mo𝖽𝖾 𝗍o 𝖽𝖾g𝗋𝖾𝖾𝗌
Degree

"R𝖾𝗌𝖾𝗍 𝖽i𝗌𝗉l𝖺y (16x7)
ClrHome
```

(See [8XP file here](https://github.com/Darmo117/TI-83_Compiler/files/8537851/Closure.Program.v2.zip))

It might be a bit hard to tell based on the Github font, but some of those characters in the comments are not the standard lowercase letters, but appear to be some kind of unicode international variation. They look quite odd in some text editors. 

Is that something to do with TI's encoding? Or a quirk of your decompiler?

Anyway, I raise this simply to have the issue logged somewhere, but it's not a high priority to have this fixed. It's for a side project and I wouldn't want you to invest hours on it (as I know some of these kinds of issues can be gnarly) when I don't even know how much use it will get.

Thanks a lot for the work you've put into it already, though. 😄

**Comment by SimonEast** [comment]
Oh, and also, I thought I could maybe manually decompile by copying and pasting my code from TI Connect CE into a text editor, but then when attempting to compile it again your compiler throws many errors on characters it doesn't understand. Here's 3 examples, but there could be more:

```
{0,0}→⌊COORD
tan(M/C)*­1+90+(C≥0)180→B
RPr(C,M)→D
```

([View full text version](https://github.com/Darmo117/TI-83_Compiler/files/8537973/closure.zip))

1. `LCOORD` is a custom list. The "⌊" symbol doesn't seem to be recognized.
2. That was originally tan<sup>-1</sup>
3. That was originally R►Pr(

But this could all be because TI Connect has its own way of representing TI tokens in ASCII/Unicode that differ to how your app does it.

So again don't stress too much if fixing this is a lot of work. It might not be worth the effort.

**Comment by DamiaV** [comment]
Hi, thanks for the feedback!

Concerning lowercase letters, I changed how they are represented. All latin upper- and lowercase letters from the calculator are represented by their ASCII equivalent in the compiler. On the other hand, all letterlike variables (a from e, u, v, w, etc.) are represented by letterlike Unicode symbols: 𝖺 (U+1D5BA), 𝖻 (U+1D5BB), etc. So in your example, you may have used those tokens instead of the calculator’s lowercase letters. I chose this as it seemed more natural to me. You can check all updated tokens and their alternatives [on the wiki](https://github.com/Darmo117/TI-83_Compiler/wiki/Instructions)

Regarding your second message, yes, TI-Connect uses its own character set. For instance, the `` character after `tan` is U+F005 which is in one of Unicode’s private use area.

I could not check the compatibility with TI-Connect as I was not able to run it properly on my Linux machine.
